from __future__ import annotations

from openpyxl.workbook.workbook import Workbook


# Excel calculation engine version written by current Microsoft 365 builds.
# A non-zero calcId prevents Excel from treating every generated workbook as if
# it came from an unknown/ancient calculation engine and rebuilding all formula
# caches on every open.  Existing non-zero IDs are preserved.
CURRENT_EXCEL_CALC_ID = 191029


def configure_incremental_excel_recalculation(workbook: Workbook) -> None:
    """Use Excel's dependency-based automatic calculation without full rebuilds.

    openpyxl writes formulas but does not evaluate them. Excel will calculate
    formula cells in Automatic mode as needed, while ``fullCalcOnLoad`` and
    ``forceFullCalc`` would unnecessarily force the whole workbook (tens of
    thousands of cells in real projects) to recalculate every time it opens.
    """

    calculation = workbook.calculation
    calculation.calcMode = "auto"
    calculation.fullCalcOnLoad = False
    calculation.forceFullCalc = False
    calculation.calcOnSave = True
    if not calculation.calcId:
        calculation.calcId = CURRENT_EXCEL_CALC_ID


def request_full_excel_recalculation(workbook: Workbook) -> None:
    """Explicit escape hatch for repair/debug workflows that need a full rebuild."""

    calculation = workbook.calculation
    calculation.calcMode = "auto"
    calculation.fullCalcOnLoad = True
    calculation.forceFullCalc = True
    calculation.calcOnSave = True
    calculation.calcId = 0




def request_initial_manual_excel_recalculation(workbook: Workbook) -> None:
    """Request one full Excel calculation on first open, then remain Manual.

    Create Progress writes formula dependencies that openpyxl cannot evaluate.
    Excel therefore needs one initial full calculation to establish formula/chart
    caches.  The workbook still opens in Manual mode so subsequent editing stays
    lightweight; F9 recalculates on demand and Save recalculates via calcOnSave.
    """
    calculation = workbook.calculation
    calculation.calcMode = "manual"
    calculation.fullCalcOnLoad = True
    calculation.forceFullCalc = True
    calculation.calcOnSave = True
    # Zero tells Excel that cached results must be rebuilt by its own engine.
    calculation.calcId = 0

def configure_live_save_recalculation(workbook: Workbook) -> None:
    """LW-8: keep lightweight dashboard formulas dormant during editing.

    Live Workbook deliberately has no large derived formula matrices. Excel is
    placed in Manual mode and asked to calculate before Save. This applies only
    to the small Dashboard/Activity interaction formulas; cached Monthly values
    are regenerated by Progress Studio Live Rebuild, not by Excel itself.
    """
    calculation = workbook.calculation
    calculation.calcMode = "manual"
    calculation.fullCalcOnLoad = False
    calculation.forceFullCalc = False
    calculation.calcOnSave = True
    if not calculation.calcId:
        calculation.calcId = CURRENT_EXCEL_CALC_ID


def configure_user_driven_save_recalculation(workbook: Workbook) -> None:
    """Use the explicit F9 / Save formula-calculation contract for final files.

    Final Progress Studio workbooks stay in Manual calculation mode while the
    user edits them. F9 recalculates Excel formulas and Excel is instructed to
    calculate formulas again before Save. Python-generated snapshots/caches are
    intentionally outside this contract and remain owned by Rebuild.
    """
    calculation = workbook.calculation
    calculation.calcMode = "manual"
    calculation.fullCalcOnLoad = False
    calculation.forceFullCalc = False
    calculation.calcOnSave = True
    if not calculation.calcId:
        calculation.calcId = CURRENT_EXCEL_CALC_ID
